[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@account-abstraction/contracts/=lib/account-abstraction/contracts/"
]

[profile.ci]
fuzz.runs = 10000
invariant.runs = 1000

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
local = "http://localhost:8545"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }